---
title: "Permutation testing"
output:
  word_document: default
  html_document: default
---

```{r, warning=F, message=F, echo=F}
require(tidyverse)
permCols=function(col.names=c("n1","n2")) {
  M[,col.names]=M[,sample(colnames)]
  M }
```

```{r Set up SELECT format test df, echo=F}
haul.no=c(1,1,1,2,2,3,3,4,4,4,5,5)
nhauls=length(unique(haul.no))
Gear=c("T0","T45","T0","T45","T0")[haul.no]
Haul=c("One","Two","Three","Four","Five")[haul.no]
lgth=c(1,2,3,1,2,1,2,1,2,3,1,2)
n1=c(3,6,1,0,0,2,1,0,0,0,1,6)
n2=c(0,0,0,4,5,0,0,4,5,6,0,0)
q1=rep(c(0.5,1,0.6),c(5,2,5))
q2=rep(c(1,1,1),c(5,2,5))
DF=data.frame(Gear,Haul,lgth,n1,n2,q1,q2)
DF3=DF2=rbind(DF,transform(DF,Haul=paste0(Haul,"A"),n1=n1+10))
DF2$Day=rep(c("B","A"),c(12,12))
DF3$Day=rep("A",24)
n.names=c("n1","n2") #Names of n (or q) columns to be replace
```

```{r, eval=F, echo=F}
## EASY
## Testing unpaired permuting of SELECT format data, no blocking (by Day)
df=DF
#HaulNum=as.numeric(as.factor(df$Haul))
#n.hauls=length(unique(df$Haul))
haulgrp=df |> group_by(Haul) |> summarize (haulgrp=unique(Gear)) |>
           data.frame()
haulgrp$permgrp=sample(haulgrp$haulgrp)
haulgrp
permuted.hauls=haulgrp$Haul[haulgrp$haulgrp!=haulgrp$permgrp]
permuted.obs=(df$Haul %in% permuted.hauls)

df[permuted.obs,n.names]=df[permuted.obs,rev(n.names)]
df$Permuted=permuted.obs
df
```

# Testing within-block unpaired permuting of SELECT format data

**Here, block is day and it is necessary to preserve Gear effort within block**

**Haul must be a unique haul identifier OVER ALL hauls.**



## Permuting data


```{r}
df.perm=df=DF2
nhauls=length(unique(df$Haul))
#Obtain the unique grp value for each block-haul combo
#NB, grouping of Day and Haul is sorted alphabetically
haulgrp= df |> group_by(Day,Haul) |> 
  summarize (grp=unique(Gear), .groups = "drop_last") 
#haulgrp tibble is still grouped by day, so slice_sample is within day
permgrp= haulgrp |> slice_sample(n=nhauls)
#Identify which hauls are permuted
permuted.hauls=haulgrp$Haul[haulgrp$grp!=permgrp$grp]
#Identify the permuted rows in the data frame, and permute
permuted.obs=(df$Haul %in% permuted.hauls)
df.perm[permuted.obs,n.names]=df[permuted.obs,rev(n.names)]
df.perm$Permuted=permuted.obs
```

## Test and permuted data
```{r}
df
df.perm
```
## Repeat with a one-level blocking variable (i.e., no blocking)

```{r}
df.perm=df=DF3
nhauls=length(unique(df$Haul))
#Obtain the unique grp value for each block-haul combo
#NB, grouping of Day and Haul is sorted alphabetically
haulgrp= df |> group_by(Day,Haul) |> 
  summarize (grp=unique(Gear), .groups = "drop_last") 
#haulgrp tibble is still grouped by day, so slice_sample is within day
permgrp= haulgrp |> slice_sample(n=nhauls)
#Identify which hauls are permuted
permuted.hauls=haulgrp$Haul[haulgrp$grp!=permgrp$grp]
#Identify the permuted rows in the data frame, and permute
permuted.obs=(df$Haul %in% permuted.hauls)
df.perm[permuted.obs,n.names]=df[permuted.obs,rev(n.names)]
df.perm$Permuted=permuted.obs
```

## Test and permuted data
```{r}
df
df.perm
```

<!--

## Paired permuting of SELECT format data

**No need for blocking since data are paired.**

```{r, echo=F, eval=F}
df=DF
permdf = df |> group_by(haul) |> do(permCols(.))
permdf

df=DF
testy=function(n1,n2) n1+n2

permdf = df |> group_by(haul) |> mutate(permute=(0.5<runif(1)) ) |>
               mutate(n1=ifelse(permute,n2,n1),n2=ifelse(permute,n1,n2))
permdf


permdf = df |> group_by(haul) |> mutate( ifelse(runif(1)<0.5,n1,n2))
permdf

permdf = df |> group_by(haul) |> reframe( permCols(n1,n2))
permdf
```

-->
