---
title: 'A SELECTion of SELECTivity curves'
author: "Russell Millar"
output:
  word_document: default
  pdf_document: default
  html_document:
    df_print: paged
editor_options: 
  markdown: 
    wrap: 80
---

```{r}
require(SELECT)
lenseq=21:100
nlens=length(lenseq)
M=rep(1,nlens) #Hypothetical meshsize
```

# Gillnet curves
```{r}
SelnCurves=matrix(NA,80,8)
colnames(SelnCurves)=c("normal","gamma","lognormal1","lognormal2","binormal1",
                       "binormal2","bilognormal1","bilognormal2")
                      
SelnCurves[,1]=selncurves("re.norm.loc")(lenseq,M,c(50,10))
SelnCurves[,2]=selncurves("re.gamma")(lenseq,M,c(6,10))
SelnCurves[,3]=selncurves("re.lognorm")(lenseq,M,c(4,0.25))
SelnCurves[,4]=selncurves("re.lognorm")(lenseq,M,c(4.25,0.5))
SelnCurves[,5]=selncurves("re.binorm.sca")(lenseq,M,c(40,10,70,10,0.7))
SelnCurves[,6]=selncurves("re.binorm.sca")(lenseq,M,c(50,10,60,20,0.7))
SelnCurves[,7]=selncurves("re.bilognorm")(lenseq,M,c(4,0.15,4.4,0.2,0.7))
SelnCurves[,8]=selncurves("re.bilognorm")(lenseq,M,c(4,0.25,4.5,0.25,0.7))

#jpeg("GillnetCurves.jpg",width=1200,height=900,pointsize=20)
par(mfrow=c(4,2),mar=c(1,4,1,4))
for(i in 1:8) {
  Curve=colnames(SelnCurves)[i]
  plot(lenseq,SelnCurves[,i],type="l",ylab=Curve,xaxt="n",yaxt="n")
}
#dev.off()
```
# Trawl curves (monotone increasing)
```{r}
SelnCurves=matrix(NA,80,4)
colnames(SelnCurves)=c("logistic","richards1","richards2","richards3")
                      
SelnCurves[,1]=selncurves("re.logistic")(lenseq,M,c(-12,0.2))
SelnCurves[,2]=selncurves("re.richards")(lenseq,M,c(-14,0.2,1))
SelnCurves[,3]=selncurves("re.richards")(lenseq,M,c(-80,1,3))
SelnCurves[,4]=selncurves("re.richards")(lenseq,M,c(-5,0.1,-1))

par(mfrow=c(2,2),mar=c(1,4,1,4))
for(i in 1:4) {
  Curve=colnames(SelnCurves)[i]
  plot(lenseq,SelnCurves[,i],type="l",ylab=Curve,xaxt="n",yaxt="n",ylim=c(0,1))
}
```


